### ISSUE TITLE
BC26 module cannot upload @ win VScode

### ISSUE THREAD

**Issue by D-zz** [Wiz-IO/platform-quectel#15]
Board： BC26-TE-B

Configuring upload protocol...
Looking for upload port...
Use manually specified: COM3
Uploading: program
Waiting module for POWER-ON or RESET <===========================> DONE
Starting <========
ERROR: EPP Answer
*** [upload] Explicit exit, status 2

**Comment by Wiz-IO** [comment]
more info? module firmware? platform version?
![Untitled](https://user-images.githubusercontent.com/14574834/67268622-96f2c680-f4bd-11e9-97e6-e80685c312d8.png)

**Comment by D-zz** [comment]
@Wiz-IO  Thank you very much. More info as below：

![image](https://user-images.githubusercontent.com/7736382/67274179-814bc400-f4f2-11e9-9a96-f37d7aea9331.png)

**Comment by Wiz-IO** [comment]
try edit this value
https://github.com/Wiz-IO/platform-quectel/blob/master/builder/frameworks/MT2625.py#L193

**Comment by Wiz-IO** [comment]
or enable DEBUG
https://github.com/Wiz-IO/platform-quectel/blob/master/builder/frameworks/MT2625.py#L61

**Comment by D-zz** [comment]
My board is BC26-TE-B，it is same of BC66-TE-B？

**Comment by Wiz-IO** [comment]
but maybe chip-set ID is other

**Comment by Wiz-IO** [comment]
are you update BC26 with BC66 firmware?

**Comment by D-zz** [comment]
@Wiz-IO  Yes ，i update BC26 with BC66 firmware
![image](https://user-images.githubusercontent.com/7736382/67280027-da215980-f4fe-11e9-92db-b850f8812ded.png)

**Comment by D-zz** [comment]
what's the error of “EPP Answer” means ?

**Comment by D-zz** [comment]
when i use BC26, is same problem of use BC66

![image](https://user-images.githubusercontent.com/7736382/67280412-ab57b300-f4ff-11e9-8803-a4f3c9087d32.png)

**Comment by Wiz-IO** [comment]
“EPP Answer” means: no answer from first bootloader

**Comment by maximevince** [comment]
If anyone is still wondering, I ran into the same issue, and it can be solved as follows:
- the BC66 needs some more time after booting, before receiving the expected `EPP` reply. (Almost 500us)

This can be seen in the capture below:
![image](https://user-images.githubusercontent.com/3796135/113131388-6f10a200-921d-11eb-9ca3-8ae574c4218f.png)

It can be solved by modifying ~/.platformio/platforms/quectel/builder/frameworks/MT2625.py by adding `time.sleep(0.5)` or similar to line 384:

```diff
diff --git a/builder/frameworks/MT2625.py b/builder/frameworks/MT2625.py
index e9215ac..898a8cc 100644
--- a/builder/frameworks/MT2625.py
+++ b/builder/frameworks/MT2625.py
@@ -381,6 +381,8 @@ class MT2625:
             self.s.write(data[:1024])                        
             data = data[1024:]  
             PB_STEP()   
+        # Give the chip some time
+        time.sleep(0.5)
         ASSERT( self.cmd("", 10) == b"\x1D\x3D\0\0\0\0\0\0\0\0", "EPP Answer" ) 
         self.uart_speed_max()           
         # DA_2
```

**Comment by Wiz-IO** [comment]
Thanks @maximevince

**Comment by maximevince** [comment]
Thanks @Wiz-IO for your platformio framework. I got a custom application running on a BC66 in no time. Awesome!
