### ISSUE TITLE
Issue in MC60 MQTT

### ISSUE THREAD

**Issue by Naveenkato** [Wiz-IO/platform-quectel#19]
Sir,
    We are having troubles using the MQTT AT commands on MC60.module replies OK for all commands such as AT+QMTCFG=keepalive,version,ssl,timeout.But it always returns simply error without any errror code for AT+QMTOPEN=1,“m16.cloudmqtt.com”,13537

**Comment by Wiz-IO** [comment]
Hi
This "issue" is for Quectel suport...

**Comment by Naveenkato** [comment]
OK sir,I saw your reply in Quectel support team,then only i ask to you.
Thank you sir
