### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mampez** [Wiz-IO/platform-quectel#2]
Hi Georgi:

I'm really fan of this project. But, do you have documentation about the functions (API) and more examples? 

I'm trying to do things like: wake up the device using a GPIO (interrupt), read/write using the UART, communicate via i2c...

Thank you for your job! It's a great stuff.

M.

**Comment by Wiz-IO** [comment]
Hi, 
sorry, I am not ready with all ... API, libraries, documents .... the poject is very big for alone developer
First I want to make stable "cores"

Quectel have docs about OpenCPU - ask support (I am not authorized to post information)

The other: 
BC66 is normal OpenCPU, FreeRTOS, lwIP, mbedtls ....
BG96 is Qualcomm ThreadX "standart" API
EC25 is normal Linux GNU applications
M66, MC60 - OpenCPU 
if you need some - just ask me on email

All Quectel SDKs have examples...

**Comment by mampez** [comment]
Thanks Wiz-IO,

I understand how difficult this is and what should be the first steps. I will continue your project and try to help testing it ;-)
