### ISSUE TITLE
Flashing using PlatformIO fails for BC66-NA

### ISSUE THREAD

**Issue by bart-iot** [Wiz-IO/platform-quectel#25]
Hi there, 

I am using your platform for developing openCPU code for a BC66-NA module. It works great but flashing using PlatrformIO fails. Flashing the binary with IoT flash tool works fine. 
PlatformIO reports this:

> Use manually specified: COM9
> Uploading: program
> Waiting module for POWER-ON or RESET <=========================> DONE
> Starting <========
> ERROR: EPP Answer
> *** [upload] Explicit exit, status 2

Monitoring using PlatformIO works fine. 

Any ideas what can cause this?

**Comment by Wiz-IO** [comment]
Hi
USB driver...

**Comment by Wiz-IO** [comment]
BC66-**NA** ? I not have NA module for test
and this platform not support NA modules...

**Comment by bart-iot** [comment]
Thanx for your reply. I also have a BC66NB evaluation kit, that has the same problem with flashing. I installed the drivers according the documentation, but problem stays.
I think there is not really a big difference between BC66NB or BC66-NA .. at least the delivered SDK is identical

**Comment by Wiz-IO** [comment]
IoT Tool work? ( original flasher )

**Comment by bart-iot** [comment]
Yes that works fine.

**Comment by Wiz-IO** [comment]
no idea .... use IoT Tool ... app bin file is in project build folder

**Comment by bart-iot** [comment]
Yes I already did that, so will keep doing that. Thanx. :)

**Comment by amaljayaprakash** [comment]
i am also getting the same error.. but iot flash tool works file
![Screenshot from 2021-03-03 18-02-17](https://user-images.githubusercontent.com/20471391/109806390-a99d1400-7c4a-11eb-8526-95f42c8cfd7d.png)

**Comment by Wiz-IO** [comment]
install drivers or use IoT Falsh Tool

**Comment by BionicSystemSolutions** [comment]
Can you link to a download page for this flash tool?

**Comment by Wiz-IO** [comment]
https://github.com/Wiz-IO/LIB/blob/master/quectel/IoT_FlashTool_v2.7.3.zip

**Comment by maximevince** [comment]
I ran into a similar issue (using BC66), see https://github.com/Wiz-IO/platform-quectel/issues/15#issuecomment-810963028 for a possible solution.
