### ISSUE TITLE
Error: Multiple ways to build the same target were specified

### ISSUE THREAD

**Issue by 1iveowl** [Wiz-IO/platform-quectel#27]
I trying to get up and running, but I'm stuck trying to build the `bc66_cpp_hello` example:

![BC66_CCP_HELLO](https://user-images.githubusercontent.com/12871120/78914884-61519200-7a8b-11ea-815b-880d73e461b7.jpg)

I have verified that the correct Quectel platform is installed: 
![Quectel platform](https://user-images.githubusercontent.com/12871120/78915088-b1305900-7a8b-11ea-93e3-b5bb6f3af838.jpg)

A hint for how to proceed would be great appreciated.

**Comment by Wiz-IO** [comment]
Hi
you have two main files in project

**Comment by Wiz-IO** [comment]
![1](https://user-images.githubusercontent.com/14574834/78917219-4258fd00-7a97-11ea-997b-cf1f5cf447f2.jpg)

**Comment by Wiz-IO** [comment]
![2](https://user-images.githubusercontent.com/14574834/78917492-9663e180-7a97-11ea-839e-e02d24e88d77.jpg)

**Comment by 1iveowl** [comment]
Ahh, of course. I just downloaded the example. Didn't look too close at the code. 

Not sure why the example has two mains? Anyhow I commented out the C++ one, changes its filename and now it compiles.

**Comment by Wiz-IO** [comment]
if you want to do experiments with C++
create new OpenCPU project, then rename main.c to main.cpp then follow the example
https://github.com/Wiz-IO/platformio-quectel-examples/blob/master/BC66_SDK/CPP/BC66_CPP_HELLO/src/main.cpp

sorry, is only one example... I need time to make other...

**Comment by 1iveowl** [comment]
> sorry, is only one example... I need time to make other...

No problem. I should have looked at the code.

I've tried with both c and c++. I can compile both however with `main.cpp` I get a squiggly line under `#include <os_wizio.h>`, and with `main.c` I get squiggly lines under all the includes except `stdint.h` and `stddef.h`. Why is that? As I said I can compile them just fine.

**Comment by Wiz-IO** [comment]
this folder <**wizio**> is my drivers and helpers for Arduino and C++ projects
named is ... os_wizio.h 
https://github.com/Wiz-IO/framework-quectel/tree/master/opencpu/bc66/SDK15/wizio

this drivers can not be used in normal OpenCPU project.... is not included in search path
for OpenCPU you need to follow Quectel SDK
**include** and **ril** folder
https://github.com/Wiz-IO/framework-quectel/tree/master/opencpu/bc66/SDK15/include

**Comment by 1iveowl** [comment]
When trying to compile the `tcp_http` example I get: 
> fatal error: nbClient.h: No such file or directory

Am I missing another lib? 

`framework-quectel` is installed.

**Comment by Wiz-IO** [comment]
for last platform version examples is there
https://github.com/Wiz-IO/platformio-quectel-examples/tree/master/BC66_SDK

wiki is:
https://github.com/Wiz-IO/platform-quectel/wiki/SDK-BC66
