### ISSUE TITLE
what changes need to make platform-quectel to work with new M66FAR02A06BT version of M66

### ISSUE THREAD

**Issue by umeshwalkar** [Wiz-IO/platform-quectel#31]
Hello guys.

Using **platform-quectel** and it's **Arduino-Quectel-M66** (M66FAR01A12BT firmware ), I developed a gprs gateway/logger application and it is working fine.
Then i came across a requirement for SSL connection for HTTP and MQTT.
using AT commands and QCOM I tried to connect to AWS Server and it wasn't worked though AWS server setup is fine. my AWS setup is according to [aws-serverless-and-an-esp32](https://aws.amazon.com/blogs/compute/building-an-aws-iot-core-device-using-aws-serverless-and-an-esp32/). and working with ESP32.

Quectel FAEs insisted me to work with latest firmware (M66FAR02A06BT). They said SSL my not work with old firmware. 
SSL with AWS (HTTPS and MQTTS) is working with this firmware.

So, My question is how can i upgrade the  platform-quectel and Arduino-Quectel-M66 to make work with this new firmware. is it possible to make it work, If yes, what things I need to look after.

Please respond.
Thanks & regards,
Umesh

**Comment by Wiz-IO** [comment]
Hi
as OpenCPU - you can update firmware
as Arduino - no - port use some direct calls to kernel and  this firmware not support SSL
