### ISSUE TITLE
Platformio errors

### ISSUE THREAD

**Issue by luisgcu** [Wiz-IO/platform-quectel#36]
hello I am having problems when compiling the examples in platformio. 
each example give me an different error.. i think some missing libraries? could you please point me the right direction.. I have 2 olimex dev  NB-IoT-BC66-ANT.
Thanks a lot.
![image](https://user-images.githubusercontent.com/11203310/86864702-a93c8100-c09b-11ea-81cd-40f3b197b37b.png)

**Comment by Wiz-IO** [comment]
Hi
you use old examples...

https://github.com/Wiz-IO/platformio-quectel-examples/tree/master/BC66_SDK
