### ISSUE TITLE
"ERROR: Boot timeout" on Mac OS when uploading through platformio. 

### ISSUE THREAD

**Issue by OlineStaerke** [Wiz-IO/platform-quectel#38]
Hi, Im getting the error Boot Timeout, when I upload and click the start button on the board. 

Is it possible to fix? 

This is what I have : 

[env:bc66-te-b]

platform = quectel
board = bc66-te-b
framework = arduino
board_build.firmware = BC66NBR01A10
upload_port = /dev/tty.SLAB_USBtoUART3
monitor_port = /dev/tty.SLAB_USBtoUART3
monitor_speed = 9600

Thank you

**Comment by Wiz-IO** [comment]
Hi
your problem is USB drivers
contact with your Quectel support and ask How to install drivers
I not have Mac - cant test

**Comment by OlineStaerke** [comment]
Hi thanks, do you know which driver?

**Comment by OlineStaerke** [comment]
I changed drivers, and now I get the following error:

Waiting module for POWER-ON or RESET <=========================> DONE
Starting <========
ERROR: EPP Answer
*** [upload] Explicit exit, status 2
====================================================================== [FAILED] Took 5.96 seconds ======================================================================
The terminal process "pio 'run', '--target', 'upload', '--environment', 'bc66'" terminated with exit code: 1.

**Comment by Wiz-IO** [comment]
no idea about Mac drivers... I just know it works
btw: ERROR: EPP Answer - mean: no answer from module
