### ISSUE TITLE
Request: support for M66-DS

### ISSUE THREAD

**Issue by umeshwalkar** [Wiz-IO/platform-quectel#39]
Hello,

I have developed a gateway application on M66 using arduino framework. now I came across requirement where i need to give dual sim support.
is it possible to port M66 framework to M66DS?

**Comment by Wiz-IO** [comment]
Hi, nope
work only with M66 - M66FAR01A12BT1

**Comment by Wiz-IO** [comment]
btw: the platform is Opensource - if someone make port will work

**Comment by umeshwalkar** [comment]
Ok.

I found this link for M66DS documentation but downloadable things are not available.

https://www.quectel.com/ProductDownload/M66-DS_OpenCPU_SDK.html

**Comment by Wiz-IO** [comment]
ask Quectel support
