### ISSUE TITLE
Bug in math.h in toolchain

### ISSUE THREAD

**Issue by aakash4895** [Wiz-IO/platform-quectel#40]
Whenever I use sqrt function from math.h library QFlash shows this error
![image](https://user-images.githubusercontent.com/74182185/100079195-5efd4600-2e6a-11eb-8586-44739cec4eba.png)

But when I the Quectel sdk which uses a different toolchain there is no such errors

**Comment by Wiz-IO** [comment]
Hi
M66 and MC60 are 95% _"identical"_ as SoC...
seem as Quectel uploader issue.... no idea for now

screenshots - same example - changed only module and platform from INI...

![MC60](https://user-images.githubusercontent.com/14574834/100083366-09b53a80-2e52-11eb-94bf-289d334fe3fc.jpg)

**Comment by Wiz-IO** [comment]
![M66](https://user-images.githubusercontent.com/14574834/100084358-577e7280-2e53-11eb-8c4d-5e348eb2abc4.jpg)

**Comment by aakash4895** [comment]
I solved the problem by using the toolchain from Sourcery Codebench Lite given by Quectel in platform io
![image](https://user-images.githubusercontent.com/74182185/100089502-ca014980-2e77-11eb-91db-f2c27263ac45.png)

![image](https://user-images.githubusercontent.com/74182185/100089549-dbe2ec80-2e77-11eb-8161-d5b85e20dc30.png)

![image](https://user-images.githubusercontent.com/74182185/100089597-ef8e5300-2e77-11eb-9f26-4d7ce7524875.png)

**Comment by aakash4895** [comment]
![image](https://user-images.githubusercontent.com/74182185/100089670-12206c00-2e78-11eb-9579-2e80c8639980.png)

**Comment by Wiz-IO** [comment]
Nice
I will ask Quectel

IF you need any compiler keys ( compilers is different ) edit here
https://github.com/Wiz-IO/platform-quectel/blob/master/builder/frameworks/opencpu-mc60.py#L63

**Comment by Wiz-IO** [comment]
I found the bug.... will test and update soon

**Comment by aakash4895** [comment]
Nice 

Thank you

**Comment by Wiz-IO** [comment]
please test...

only this file is different
https://github.com/Wiz-IO/platform-quectel/blob/master/builder/frameworks/mc60.py

**Comment by aakash4895** [comment]
will test and let you know
