### ISSUE TITLE
READ GPS DATA

### ISSUE THREAD

**Issue by daviidmart** [Wiz-IO/platform-quectel#41]
I am working with the EC25, it has a GNSS integrated, I would like to know if there is a way to read the data to send it through MQTT?

**Comment by Wiz-IO** [comment]
send AT command to enable GPS, open uart and read NMEA

**Comment by Wiz-IO** [comment]
[example_at_gps.zip](https://github.com/Wiz-IO/platform-quectel/files/5648381/example_at_gps.zip)

**Comment by daviidmart** [comment]
This works with Arduino?

**Comment by daviidmart** [comment]
Thank you very much for the help. This works with Arduino?

**Comment by Wiz-IO** [comment]
OpenLinux SDK
Arduino port is not shared yet

**Comment by daviidmart** [comment]
Internally use QuecOpen?

**Comment by daviidmart** [comment]
If I make a donation, is it possible to add the GPS function and GPIO in Arduino?

**Comment by Wiz-IO** [comment]
in Arduino... just follow the QuecOpen example
