### ISSUE TITLE
ADB

### ISSUE THREAD

**Issue by daviidmart** [Wiz-IO/platform-quectel#43]
I am working with the EC25-A module, do I need to have a special firmware?

I can't get the device to work in adb.  I already installed all the drivers.

OS Windows 10

**Comment by Wiz-IO** [comment]
Hi
read this:
https://forums.quectel.com/t/ec-25e-software-development/2707

or connect to your local Quectel support... I forgot what it was

**Comment by Wiz-IO** [comment]
try and this adb
https://github.com/Wiz-IO/tool-quectel/tree/master/windows/ec2x

**Comment by daviidmart** [comment]
So no special firmware is needed?

**Comment by Wiz-IO** [comment]
all with ADB enabled
