### ISSUE TITLE
f

### ISSUE THREAD

**Issue by daviidmart** [Wiz-IO/platform-quectel#45]
Hi!

I am working with a development board that I create with the EC25-A module but I cannot get the device to appear in the ADB. Do I need a special firmware?

Quectel people in my country do not give me a solution to be able to use QuecOpen, they only tell me that it is only for large manufacturers 😪

Regards

![DEVBOARD](https://user-images.githubusercontent.com/10666050/110580672-c051d800-812e-11eb-88ac-b26d7707065f.jpg)

**Comment by Wiz-IO** [comment]
https://forums.quectel.com/search?q=adb
