### ISSUE TITLE
Debug Output

### ISSUE THREAD

**Issue by pcasper90** [Wiz-IO/platform-quectel#46]
![1](https://user-images.githubusercontent.com/81177358/112018410-d13b1a00-8b2e-11eb-92ae-bf2cb84bc7f9.PNG)
![2](https://user-images.githubusercontent.com/81177358/112018416-d1d3b080-8b2e-11eb-9b3f-2ce0b6293949.PNG)
![3](https://user-images.githubusercontent.com/81177358/112018418-d26c4700-8b2e-11eb-82a7-cde45770a0e9.PNG)

Hello,
i have problems with the debug output. 
I configured baud rate 115200 and port7 is interface2.

**Comment by Wiz-IO** [comment]
seems like a Quectel problem...
reflash module - IF problem again - ask your  local Quectel support

**Comment by pcasper90** [comment]
local quectel support does not answer ..

**Comment by Wiz-IO** [comment]
https://www.quectel.com/support/contact.htm
https://forums.quectel.com/

**Comment by pcasper90** [comment]
I flashed BC66NBR01A04V01 but still the same problem.
Now i created a topic at quectel forum. 

Support Contact formular and support@quectel.com don't answer me ...

**Comment by Wiz-IO** [comment]
BC66NBR01A10  recomended 
... 04 ... is for old SDK

**Comment by pcasper90** [comment]
BC66NBR01A04V01 was the only version i found on the internet.
but last night i got contact to quectel support. maybe i can get BC66NBR01A10 from quectel.

**Comment by nestorayuso** [comment]
ftp://staging.olimex.com/BC66/

**Comment by pcasper90** [comment]
Thank you now i flashed BC66NBR01A10 ;)
But still the same issue for interface 2.

**Comment by Wiz-IO** [comment]
what is "interface 2" ? and port7 ??

**Comment by pcasper90** [comment]
![interface2](https://user-images.githubusercontent.com/81177358/112111259-3dac2c80-8bb4-11eb-85c8-6f65fe5af998.PNG)
![userguide](https://user-images.githubusercontent.com/81177358/112111264-3dac2c80-8bb4-11eb-856d-ae6207fa169d.PNG)

**Comment by pcasper90** [comment]
interface 0 for at commands and firmware flashing works fine.
or is it wrong, that i expect the debug outputs on interface2 ?

**Comment by Wiz-IO** [comment]
BC66 have only 2 UARTS

**Comment by pcasper90** [comment]
ok than i´m not sure how to understand the user guide. how can i see my debug ouput ?

**Comment by Wiz-IO** [comment]
#define DEBUG_PORT  UART_PORT0 or 1 and follow the module **UART pins**
USB interface is not supported in OpenCPU
USB is only for Firmware updates, AT commands and Service debug/log

**Comment by Wiz-IO** [comment]
work?

**Comment by pcasper90** [comment]
not yet .. but just got new infos from quectel. i will let you know when i find my problem ..

**Comment by Wiz-IO** [comment]
BC66 OpenCPU UART-s ( in red )
![bc66](https://user-images.githubusercontent.com/14574834/112190264-80e6b980-8c0d-11eb-9f59-e6e9cc95fc88.jpg)

**Comment by pcasper90** [comment]
I use the bc66-te-b
![board](https://user-images.githubusercontent.com/81177358/112983320-d8c97700-915d-11eb-944a-85bcf55b5ad1.jpg)

Debug Port (Interface 2) is COM10
<img width="312" alt="10" src="https://user-images.githubusercontent.com/81177358/112983410-f26abe80-915d-11eb-9d7d-52b03cfd4a66.PNG">

But when use putty i can´t read it clear.
<img width="825" alt="11" src="https://user-images.githubusercontent.com/81177358/112983473-057d8e80-915e-11eb-9311-6ff160ed7246.PNG">

**Comment by Wiz-IO** [comment]
![Untitled-1](https://user-images.githubusercontent.com/14574834/112984477-9ad15080-9167-11eb-9008-095663d584bd.jpg)

**Comment by pcasper90** [comment]
I want to use it without Arduino. So framework should be opencpu.
![12](https://user-images.githubusercontent.com/81177358/112985704-cef54300-9160-11eb-8557-869f8c401c01.PNG)

**Comment by pcasper90** [comment]
How can i see [APP] begin and [RIL] ready?

**Comment by Wiz-IO** [comment]
![Untitled-1](https://user-images.githubusercontent.com/14574834/112987487-74151900-916b-11eb-8c0a-bfa2b636a1e2.jpg)

**Comment by pcasper90** [comment]
ok you use for both the same COM port. now i have a problem while uploading the program
![13](https://user-images.githubusercontent.com/81177358/112989768-90ae5280-9165-11eb-8f34-66ab5df4f9e5.PNG)

**Comment by Wiz-IO** [comment]
install drivers
![Untitled-1](https://user-images.githubusercontent.com/14574834/112990250-804ea580-916e-11eb-91b7-ecf9b87ea2b2.jpg)
