### ISSUE TITLE
How far off is a BG77 framework?

### ISSUE THREAD

**Issue by maximevince** [Wiz-IO/platform-quectel#48]
Hey @Wiz-IO ,

Thanks for the very nice work. I have been playing a few days with your BC66 framework, which works really nicely.
I was wondering how far off a BG77 port is?

I realize it's a different beast; being based on ThreadX instead of OpenCPU.
Is there anything I can do to help?

**Comment by Wiz-IO** [comment]
I have no intention of releasing it - lack of interest....

**Comment by maximevince** [comment]
Ok, there is at least some interest, now :)
As I said, I am willing to help if you want.

**Comment by Wiz-IO** [comment]
the help is not the problem
BG95/55 is ready before year....
https://www.youtube.com/watch?v=1vF9Lb7n_-k
https://www.youtube.com/watch?v=MdGzIl_6uzA

**Comment by STB3** [comment]
Me too, I'm also interested in the BG77. :-)
if you need help or hardware, please tell us.
