### ISSUE TITLE
Run framework on M26

### ISSUE THREAD

**Issue by rusauth** [Wiz-IO/platform-quectel#52]
Hi is it possible to run this framework on the M26 Chinese version of M66?
What changes need to be made to make it work?

**Comment by Wiz-IO** [comment]
M26 is M66
The difference is in UART - RX & TX pins is hardware swapped :)
just select M66 and test...

**Comment by rusauth** [comment]
I managed to put the Android version true UART but nothing is happing. On Uart1 I get an echo, something garbage sometimes ok. On the Debug UART the message "Memory dump is disabled!" is coming out, so I think that the device is not flashed right. It is hard to find M26 OpenCPU SDK. 
I'm stuck, have tried to flash a different version but something just doesn't work.

**Comment by rusauth** [comment]
Do you have firmware for M26?

**Comment by Wiz-IO** [comment]
I not have... just ask from Quectel
