### ISSUE TITLE
platformio VScode quectel MC60 upload error 

### ISSUE THREAD

**Issue by m2c-chandan** [Wiz-IO/platform-quectel#53]
Hi, sir i am facing an error when i am trying to upload a code on my MC60 module from quectel, for the setup i have followed all your previous github repo its working good but just the problem i am having when i try to upload code directly from platformio using vscode. please provide some help to me as i have searched all about it but didnt find anything anywhere.
ERROR: APP: MMM`

**Comment by Wiz-IO** [comment]
Hi
PIO uploaded for MC60 is not tested ... use Quectel upload software

**Comment by m2c-chandan** [comment]
ohk, Thank you sir.
