### ISSUE TITLE
BC66-NA Cyclic reboot

### ISSUE THREAD

**Issue by mgronst** [Wiz-IO/platform-quectel#54]
Does the platform support the BC66-NA? Tried to test this example:
https://github.com/Wiz-IO/platformio-quectel-examples/blob/master/BC66_SDK/CPP/BC66_CPP_HELLO/src/main.cpp
on a BC66-NA-TE-B dev kit. Compilation and upload went find, but the led is blinking rapidly and the serial output continously prints this, that seems like some cyclic reboot:
```
F1: 0000 0000
V0: 0000 0000 [0001]
00: 0006 000C
01: 0000 0000
U0: 0000 0001 [0000]
T0: 0000 00B4
Leaving the BROM


F1: 0000 0000
V0: 0000 0000 [0001]
00: 0006 000C
01: 0000 0000
U0: 0000 0001 [0000]
T0: 0000 00B4
Leaving the BROM
```

Any tips to get it to work on this board?

**Comment by Wiz-IO** [comment]
Hi 
This platform not support NA modules
https://github.com/Wiz-IO/platform-quectel/wiki/Framework-Arduino#ini-for-bc66
