### ISSUE TITLE
Could not install platform

### ISSUE THREAD

**Issue by chandankumar1** [Wiz-IO/platform-quectel#57]
I am facing issues with installation of **https://github.com/Wiz-IO/platform-quectel** . I had already installed git scm in my system.

The error is as follows:

`(962/971)\rUpdating files: 100% (971/971)\rUpdating files: 100% (971/971), done.\nError: Could not find one of 'package.json' manifest files in the package"`

**Comment by jo95ztap** [comment]
Hello, 
I have the same problem.

How did you fix the error??
