### ISSUE TITLE
BG77 SPI with EVB (Evaluation Board)

### ISSUE THREAD

**Issue by daviidmart** [Wiz-IO/platform-quectel#59]
I’m trying to use an eink display with the SPI protocol but I can’t get it to work I always get the error QAPI_SPIM_ERROR_OPEN_FAILURE. Is this error due to the connections or do I have something wrong configured? I looked in the forum that you have used SPI with the BG95 module that is similar, I hope you can help me.

**Comment by daviidmart** [comment]
![image](https://user-images.githubusercontent.com/10666050/202054865-5834d653-1069-4448-bd24-49dbd4787da9.png)
![image](https://user-images.githubusercontent.com/10666050/202054870-aedad2d9-2315-49d7-ae12-e4a301945265.png)
![image](https://user-images.githubusercontent.com/10666050/202054876-119b331e-b06a-4cd1-b6d1-8ad0c4d6a6e5.png)

**Comment by Wiz-IO** [comment]
Hi
This platform not support BG77
Please ask support@quectel.com
