### ISSUE TITLE
manifest.json unavailable

### ISSUE THREAD

**Issue by DanKoloff** [Wiz-IO/platform-quectel#60]
I believe these two locations for manifest.json (from platform.json) are unavailable:

"https://dl.bintray.com/platformio/dl-packages/manifest.json",
"http://dl.platformio.org/packages/manifest.json"

I think bintray closed. Not sure about the other location.

This leads to error when trying to install:

Error: Could not find one of 'package.json' manifest files in the package"

I couldn't figure out alternative.

**Comment by Wiz-IO** [comment]
Тhe platform is frozen indefinitely - lack of support from stakeholders...
More precisely: because of incompetent Quectel managers

ask here: eddy.mao@quectel.com  or support@quectel.com
