### ISSUE TITLE
Quectel BG95, flashing code directly? 

### ISSUE THREAD

**Issue by camp-easy** [Wiz-IO/platform-quectel#62]
hello , i cant discover if i can flash my custom code of (eg in C) directly to the quectel bg95’s arm  cortex a7 , to make it execute it directly or if i need to use an external mcu like esp32 to make a code with AT command. thank you in advance.

**Comment by Wiz-IO** [comment]
support@quectel.com
run away from Quectel....

**Comment by camp-easy** [comment]
Sorry im new to Quectel so i dont know its issues, can you be more specific and however, do you know a module like quectel bg95 with built in lte and gnss but that is self programmable? Thank you in advance for your important support.
