### ISSUE TITLE
Arduino Pin Mapping for BC66 and BG96?

### ISSUE THREAD

**Issue by Humancell** [Wiz-IO/platform-quectel#8]
Do you have a diagram or table that shows the pin mappings for the various BC66 and BG96 pins to the Arduino environment?  (e.g. D1, D2, A1, A2, etc.)

Also, is there a mapping already for the I2C pins also if I want to use the Wire library?

**Comment by Wiz-IO** [comment]
ALL pins/periphery enumerations is as quectel api... look header files or ask documentations 

or look variant file and re-sort...
